mode: rule
mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
allow-lan: true
ipv6: false
unified-delay: true
log-level: silent
tcp-concurrent: true
find-process-mode: always

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - Mijia Cloud
    - "+.push.apple.com"

profile:
  store-selected: true
  store-fake-ip: true

ntp:
  enable: true
  write-to-system: true
  server: ntp.ntsc.ac.cn
  port: 123
  interval: 60

external-controller: 127.0.0.1:9090
external-ui: zashboard
external-ui-url: "https://v6.gh-proxy.org/https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"
bind-address: "*"

tun:
  include-uid: []
  enable: false
  device: mihoyo
  stack: mixed
  auto-route: true
  strict-route: true
  endpoint-independent-nat: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack: 
    - tcp://any:53
    - udp://any:53

dns:
  enable: true
  listen: 0.0.0.0:1053
  cache-algorithm: arc
  prefer-h3: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter-mode: rule
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter:
    - RULE-SET,CN_域,real-ip
    - RULE-SET,Fake-IP-Filter,real-ip
    - DOMAIN-KEYWORD,mtalk.google,real-ip
  default-nameserver:
    - https://1.12.12.21/dns-query
    - https://223.5.5.5/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
    "RULE-SET:CN_域":
      - https://dot.pub/dns-query
      - https://dns.alidns.com/dns-query

proxies:

p: &p
  type: http
  interval: 0
  health-check:
    enable: true
    url: 'https://cp.cloudflare.com/generate_204'
    interval: 1800
    timeout: 5000
  proxy: DIRECT
  exclude-filter: '(?i)官网|邀请|到期|流量|更新|验证|剩余|频道|长期|推广|分享|周期|我的|失联|使用|大陆'
  header:
      User-Agent:
      - "ClashMetaForAndroid/v2.11.26"
  override:
    udp: true

proxy-providers:
  订阅名:
    <<: *p
    path: ./proxy_provider/订阅名.yaml
    url: "订阅"

proxy-groups:
  - name: Proxy
    icon: "https://v6.gh-proxy.org/https://github.com/xons3974/proxy/blob/main/icon/svg/proxy.svg"
    type: select
    proxies:
      - 订阅名

  - name: AI
    icon: "https://v6.gh-proxy.org/https://github.com/xons3974/proxy/blob/main/icon/svg/ai.svg"
    type: select
    proxies:
      - 订阅名

rule-anchor:
  IPCIDR: &IPCIDR
    {type: http, behavior: ipcidr, format: mrs, interval: 86400}
  Domain: &Domain
    {type: http, behavior: domain, format: mrs, interval: 86400}

rule-providers:

  WebRTC_端/域:
    <<: *Domain
    path: ./rules/WebRTC.mrs
    url: "https://v6.gh-proxy.org/https://github.com/musiyun124/mihomo/raw/refs/heads/main/rules/WebRTC.mrs"

  Fake-IP-Filter:
    <<: *Domain
    path: ./rules/Fake-IP-Filter.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"

  CN_IP:
    <<: *IPCIDR
    path: ./rules/CN_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cnip.mrs"
  CN_域:
    <<: *Domain
    path: ./rules/CN_域.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cn.mrs"

  No-ads-all_域:
    <<: *Domain
    path: ./rules/No-ads-all.mrs
    url: "https://v6.gh-proxy.org/https://github.com/TG-Twilight/AWAvenue-Ads-Rule/raw/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"
  Adblock:
    <<: *Domain
    path: ./rules/Adblock.mrs
    url: "https://v6.gh-proxy.org/https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomo.mrs"

  Google_域:
    <<: *Domain
    path: ./rules/Google.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/google.mrs"
  Google_IP:
    <<: *IPCIDR
    path: ./rules/Google_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/google.mrs"

  AI_域:
    <<: *Domain
    path: ./rules/AI.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/ai.mrs"
  AI_IP:
    <<: *IPCIDR
    path: ./rules/AI_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/ai.mrs"

  Private_域:
    <<: *Domain
    path: ./rules/LAN.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/private.mrs"
  Private_IP:
    <<: *IPCIDR
    path: ./rules/Private_IP.mrs
    url: "https://v6.gh-proxy.org/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/privateip.mrs"

rules:
  - RULE-SET,WebRTC_端/域,REJECT
  - RULE-SET,No-ads-all_域,REJECT
  - RULE-SET,Adblock,REJECT
  - DOMAIN-KEYWORD,v6.gh-proxy,DIRECT
  - RULE-SET,Private_域,DIRECT
  - RULE-SET,Private_IP,DIRECT,no-resolve
  - AND,((NETWORK,udp),(DST-PORT,443)),REJECT
  - RULE-SET,AI_域,AI
  - RULE-SET,AI_IP,AI,no-resolve
  - DOMAIN-KEYWORD,mtalk.google,DIRECT
  - RULE-SET,Google_域,Proxy
  - RULE-SET,Google_IP,Proxy,no-resolve
  - RULE-SET,CN_域,DIRECT
  - RULE-SET,CN_IP,DIRECT,no-resolve
  - MATCH,Proxy
